"""
为需求任务.docx 各任务扩充核心代码 —— 多写完整代码
"""
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

DOC = r'C:/Users/ASUS/OneDrive/Desktop/需求任务.docx'

def mkp(doc, text, bold=False, color=None, size=Pt(10.5)):
    p = doc.add_paragraph('')
    if p.runs: p.runs[0].text = ''
    r = p.add_run(text)
    r.font.name = 'Times New Roman'
    r._element.rPr.rFonts.set(qn('w:eastAsia'), 'Times New Roman')
    r.font.size = size
    if bold: r.bold = True
    if color: r.font.color.rgb = color
    p.paragraph_format.space_before = Pt(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.1
    return p

def LABEL(doc, text): return mkp(doc, text, bold=True, color=RGBColor(0x78,0x78,0x78))
def TITLE(doc, text): return mkp(doc, text, bold=True, color=RGBColor(0x00,0x96,0x88))
def FE(doc, text): return mkp(doc, text, bold=True, color=RGBColor(0x40,0x9E,0xFF))
def BE(doc, text): return mkp(doc, text, bold=True, color=RGBColor(0xE6,0xA2,0x3C))
def C(doc, text): return mkp(doc, text, color=RGBColor(0x33,0x33,0x33))
def G(doc, text): return mkp(doc, text, color=RGBColor(0x90,0x93,0x99))
def S(doc): return mkp(doc, '')
def SP(doc):
    p = mkp(doc, '')
    p.paragraph_format.space_before = Pt(4)
    return p

def insert_before(target_para, paras):
    for p in reversed(paras):
        target_para._element.addprevious(p._element)

def insert_section(doc, anchor_text, paras):
    target = None
    for p in doc.paragraphs:
        if p.text.strip() == anchor_text:
            target = p; break
    if not target:
        print(f'  NOT FOUND: {anchor_text}'); return False
    insert_before(target, paras)
    return True

print('Opening document...')
doc = Document(DOC)

# ============================================================
# 2.1 添加干预记录 — 数据模型 + 前端按钮弹窗 + 后端API
# ============================================================
print('2.1 ...')
insert_section(doc, '2.2 干预记录列表页', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码】'),
    LABEL(doc, '📄 位置: db_model.py — Intervention 数据模型'),
    C(doc, 'class Intervention(db.Model):'),
    C(doc, '    """HR 对高风险员工采取的干预措施记录"""'),
    C(doc, "    __tablename__ = 'interventions'"),
    C(doc, '    id = db.Column(db.Integer, primary_key=True, autoincrement=True)'),
    C(doc, "    employee_id = db.Column(db.Integer, db.ForeignKey('employee_base.EmployeeNumber'),"),
    C(doc, '        nullable=False, comment="员工工号")'),
    C(doc, "    type = db.Column(db.String(20), default='其他',"),
    C(doc, '        comment="干预类型：调薪/转岗/面谈/培训/其他")'),
    C(doc, "    description = db.Column(db.Text, default='', comment='具体描述')"),
    C(doc, "    result = db.Column(db.Text, default='', comment='处理结果（可后续补充）')"),
    C(doc, "    operator = db.Column(db.String(50), default='', comment='操作人姓名')"),
    C(doc, "    created_at = db.Column(db.DateTime, default=datetime.now, comment='创建时间')"),
    C(doc, "    # 关联员工表，方便联查姓名、部门"),
    C(doc, "    employee = db.relationship('EmployeeBase', backref='interventions')"),
    SP(doc),
    LABEL(doc, '📄 位置: templates/risk_list.html — 干预按钮'),
    C(doc, '<!-- 操作列新增橙色干预按钮，点击弹出表单 -->'),
    C(doc, '<button class="layui-btn layui-btn-xs btn-intervene"'),
    C(doc, '   style="background:#ff9800;border-color:#ff9800;border-radius:6px;"'),
    C(doc, '   data-id="{{d.EmployeeNumber}}" data-dept="{{d.Department}}"'),
    C(doc, '   data-name="{{d.real_name}}">'),
    C(doc, '  <i class="layui-icon layui-icon-edit"></i> 干预'),
    C(doc, '</button>'),
    SP(doc),
    G(doc, '/* 隐藏的干预表单弹窗容器（type:1 方式渲染到 layer.open） */'),
    C(doc, '<div id="interveneFormBox" style="display:none;padding:18px 20px 0;">'),
    C(doc, '  <div class="layui-form">'),
    C(doc, '    <div class="layui-form-item">'),
    C(doc, '      <label class="layui-form-label">员工编号</label>'),
    C(doc, '      <input id="iv-emp-id" class="layui-input" readonly>'),
    C(doc, '    </div>'),
    C(doc, '    <div class="layui-form-item">'),
    C(doc, '      <label class="layui-form-label">所属部门</label>'),
    C(doc, '      <input id="iv-emp-dept" class="layui-input" readonly>'),
    C(doc, '    </div>'),
    C(doc, '    <div class="layui-form-item">'),
    C(doc, '      <label class="layui-form-label">干预类型</label>'),
    C(doc, '      <select id="iv-type">'),
    C(doc, '        <option value="调薪">调薪</option>'),
    C(doc, '        <option value="转岗">转岗</option>'),
    C(doc, '        <option value="面谈">面谈</option>'),
    C(doc, '        <option value="培训">培训</option>'),
    C(doc, '        <option value="其他">其他</option>'),
    C(doc, '      </select>'),
    C(doc, '    </div>'),
    C(doc, '    <div class="layui-form-item">'),
    C(doc, '      <label class="layui-form-label">具体描述</label>'),
    C(doc, '      <textarea id="iv-desc" class="layui-textarea"'),
    C(doc, '          placeholder="记录干预原因和具体措施"></textarea>'),
    C(doc, '    </div>'),
    C(doc, '    <div class="layui-form-item">'),
    C(doc, '      <label class="layui-form-label">处理结果</label>'),
    C(doc, '      <textarea id="iv-result" class="layui-textarea"'),
    C(doc, '          placeholder="可选，处理后补充"></textarea>'),
    C(doc, '    </div>'),
    C(doc, '  </div>'),
    C(doc, '</div>'),
    SP(doc),
    G(doc, '/* ===== JS：点击干预按钮 -> layer.open 弹窗 -> AJAX POST ===== */'),
    C(doc, '$(document).on("click", ".btn-intervene", function() {'),
    C(doc, '  var empId = $(this).data("id");'),
    C(doc, '  var empName = $(this).data("name") || "";'),
    C(doc, '  var empDept = $(this).data("dept") || "";'),
    C(doc, '  // 自动填入员工编号和部门'),
    C(doc, '  $("#iv-emp-id").val(empId);'),
    C(doc, '  $("#iv-emp-dept").val(empDept);'),
    C(doc, '  $("#iv-desc").val("");  // 清空上次输入'),
    C(doc, '  $("#iv-result").val("");'),
    C(doc, '  layer.open({'),
    C(doc, '    type: 1,  // 内容层类型，直接渲染DOM'),
    C(doc, '    title: "添加干预记录 - " + empName,'),
    C(doc, '    area: ["520px", "480px"],'),
    C(doc, '    content: $("#interveneFormBox"),'),
    C(doc, '    btn: ["确认提交", "取消"],'),
    C(doc, '    yes: function(index) {'),
    C(doc, '      var empId2 = $("#iv-emp-id").val();'),
    C(doc, '      var type = $("#iv-type").val();'),
    C(doc, '      var desc = $("#iv-desc").val().trim();'),
    C(doc, '      if(!desc) { layer.msg("请填写干预描述"); return; }'),
    C(doc, '      $.ajax({'),
    C(doc, '        url: "/predict/api/interventions",'),
    C(doc, '        type: "POST",'),
    C(doc, '        contentType: "application/json",'),
    C(doc, '        data: JSON.stringify({'),
    C(doc, '          employee_id: Number(empId2),'),
    C(doc, '          type: type,'),
    C(doc, '          description: desc,'),
    C(doc, '          result: $("#iv-result").val(),'),
    C(doc, '          operator: "{{ username }}"'),
    C(doc, '        }),'),
    C(doc, '        success: function(r) {'),
    C(doc, '          if(r.code === 0) {'),
    C(doc, '            layer.msg("干预记录已保存", {icon:1});'),
    C(doc, '            layer.close(index);'),
    C(doc, '          } else { layer.msg(r.msg, {icon:2}); }'),
    C(doc, '        }'),
    C(doc, '      });'),
    C(doc, '    }'),
    C(doc, '  });'),
    C(doc, '});'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: blueprints/predict.py — POST /predict/api/interventions'),
    C(doc, "@predict_bp.route('/api/interventions', methods=['POST'])"),
    C(doc, 'def api_interventions_create():'),
    C(doc, '    """新增干预记录"""'),
    C(doc, '    try:'),
    C(doc, '        from db_model import Intervention'),
    C(doc, '        data = request.get_json(silent=True) or request.form'),
    C(doc, "        emp_id = data.get('employee_id', type=int)"),
    C(doc, "        if not emp_id:"),
    C(doc, "            return jsonify({'code': 400, 'msg': '员工工号不能为空'})"),
    C(doc, "        intervention = Intervention("),
    C(doc, '            employee_id=int(emp_id),'),
    C(doc, "            type=data.get('type', '其他'),"),
    C(doc, "            description=data.get('description', ''),"),
    C(doc, "            result=data.get('result', ''),"),
    C(doc, "            operator=data.get('operator', session.get('username', '')),"),
    C(doc, '        )'),
    C(doc, '        db.session.add(intervention)'),
    C(doc, '        db.session.commit()'),
    C(doc, '        from utils.logger import log_action'),
    C(doc, "        log_action('添加干预记录', f'员工#{emp_id}',"),
    C(doc, "            intervention.description[:60])"),
    C(doc, "        return jsonify({'code': 0, 'msg': '添加成功',"),
    C(doc, "            'data': {'id': intervention.id}})"),
    C(doc, '    except Exception as e:'),
    C(doc, '        db.session.rollback()'),
    C(doc, "        return jsonify({'code': 1, 'msg': str(e)})"),
    SP(doc),
    LABEL(doc, '📄 位置: blueprints/predict.py — PUT / DELETE 更新和删除干预'),
    C(doc, "@predict_bp.route('/api/interventions/<int:inv_id>', methods=['PUT'])"),
    C(doc, 'def api_interventions_update(inv_id):'),
    C(doc, '    """更新干预记录（补充处理结果）"""'),
    C(doc, '    try:'),
    C(doc, '        from db_model import Intervention'),
    C(doc, '        inv = Intervention.query.get(inv_id)'),
    C(doc, "        if not inv: return jsonify({'code':404,'msg':'记录不存在'})"),
    C(doc, '        data = request.get_json(silent=True) or request.form'),
    C(doc, "        if 'type' in data: inv.type = data['type']"),
    C(doc, "        if 'description' in data: inv.description = data['description']"),
    C(doc, "        if 'result' in data: inv.result = data['result']"),
    C(doc, "        if 'operator' in data: inv.operator = data['operator']"),
    C(doc, '        db.session.commit()'),
    C(doc, "        return jsonify({'code':0,'msg':'更新成功'})"),
    C(doc, '    except Exception as e:'),
    C(doc, '        db.session.rollback()'),
    C(doc, "        return jsonify({'code':1,'msg':str(e)})"),
    SP(doc),
    C(doc, "@predict_bp.route('/api/interventions/<int:inv_id>', methods=['DELETE'])"),
    C(doc, 'def api_interventions_delete(inv_id):'),
    C(doc, '    """删除干预记录"""'),
    C(doc, '    inv = Intervention.query.get(inv_id)'),
    C(doc, "    if not inv: return jsonify({'code':404,'msg':'不存在'})"),
    C(doc, '    db.session.delete(inv); db.session.commit()'),
    C(doc, "    return jsonify({'code':0,'msg':'删除成功'})"),
])

# ============================================================
# 2.2 干预记录列表页
# ============================================================
print('2.2 ...')
insert_section(doc, '2.3 员工干预时间线', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码】'),
    LABEL(doc, '📄 位置: templates/interventions.html — 统计卡片 + 筛选 + Layui 表格'),
    C(doc, '<!-- 6 个统计卡片：总数 + 5 种干预类型 -->'),
    C(doc, '<div class="stat-cards">'),
    C(doc, '  <div class="stat-card">'),
    C(doc, '    <div class="num" id="stat-total">0</div>'),
    C(doc, '    <div class="label">总干预次数</div></div>'),
    C(doc, '  <div class="stat-card">'),
    C(doc, '    <div class="num" id="stat-salary" style="color:#409EFF;">0</div>'),
    C(doc, '    <div class="label">调薪</div></div>'),
    C(doc, '  <div class="stat-card">'),
    C(doc, '    <div class="num" id="stat-talk" style="color:#5FB878;">0</div>'),
    C(doc, '    <div class="label">面谈</div></div>'),
    C(doc, '  <div class="stat-card">'),
    C(doc, '    <div class="num" id="stat-transfer" style="color:#FF9800;">0</div>'),
    C(doc, '    <div class="label">转岗</div></div>'),
    C(doc, '  <div class="stat-card">'),
    C(doc, '    <div class="num" id="stat-train" style="color:#8B5CF6;">0</div>'),
    C(doc, '    <div class="label">培训</div></div>'),
    C(doc, '  <div class="stat-card">'),
    C(doc, '    <div class="num" id="stat-other" style="color:#909399;">0</div>'),
    C(doc, '    <div class="label">其他</div></div>'),
    C(doc, '</div>'),
    SP(doc),
    C(doc, '<!-- 筛选栏：类型下拉 + 日期范围 + 查询/重置 -->'),
    C(doc, '<div class="filter-bar">'),
    C(doc, '  <select id="filter-type">'),
    C(doc, '    <option value="">全部类型</option>'),
    C(doc, '    <option value="调薪">调薪</option>'),
    C(doc, '    <option value="面谈">面谈</option>'),
    C(doc, '    <option value="转岗">转岗</option>'),
    C(doc, '    <option value="培训">培训</option>'),
    C(doc, '    <option value="其他">其他</option>'),
    C(doc, '  </select>'),
    C(doc, '  <input type="text" id="filter-start" placeholder="开始日期" readonly>'),
    C(doc, '  <span>—</span>'),
    C(doc, '  <input type="text" id="filter-end" placeholder="结束日期" readonly>'),
    C(doc, '  <button id="btn-query">查询</button>'),
    C(doc, '  <button id="btn-reset">重置</button>'),
    C(doc, '</div>'),
    SP(doc),
    G(doc, '/* Layui 表格渲染 —— 注意 {% raw %} 包裹模板避免 Jinja2 冲突 */'),
    C(doc, 'var tableIns = table.render({'),
    C(doc, "  elem: '#intervention-table',"),
    C(doc, "  url: '/predict/api/interventions',"),
    C(doc, '  page: true, limit: 15, skin: "line",'),
    C(doc, "  where: { type: '', start_date: '', end_date: '' },"),
    C(doc, '  cols: [[ '),
    C(doc, "    {field:'employee_number', title:'员工编号', width:100},"),
    C(doc, "    {field:'department', title:'部门', width:130},"),
    C(doc, "    {field:'job_role', title:'岗位', width:140},"),
    C(doc, "    {field:'type', title:'干预类型', width:100, templet:'#typeTpl'},"),
    C(doc, "    {field:'description_short', title:'描述摘要', minWidth:200},"),
    C(doc, "    {field:'result', title:'处理结果', width:100},"),
    C(doc, "    {field:'operator', title:'操作人', width:90},"),
    C(doc, "    {field:'created_at', title:'操作时间', width:160},"),
    C(doc, "    {title:'操作', width:100, templet:'#opBar'}"),
    C(doc, '  ]],'),
    C(doc, '  done: function(res) { loadStats(); }  // 每次刷新后更新统计卡片'),
    C(doc, '});'),
    SP(doc),
    C(doc, '// 类型标签颜色映射（不同干预类型用不同颜色）'),
    C(doc, 'var typeBadgeColors = {'),
    C(doc, "  '调薪': '#409EFF', '面谈': '#5FB878', '转岗': '#FF9800',"),
    C(doc, "  '培训': '#8B5CF6', '其他': '#909399'"),
    C(doc, '};'),
    C(doc, '// 加载统计数据'),
    C(doc, 'function loadStats() {'),
    C(doc, "  $.get('/predict/api/interventions/stats', function(res) {"),
    C(doc, '    if(res.code===0) {'),
    C(doc, "      $('#stat-total').text(res.data.total||0);"),
    C(doc, "      $('#stat-salary').text(res.data['调薪']||0);"),
    C(doc, "      $('#stat-talk').text(res.data['面谈']||0);"),
    C(doc, "      $('#stat-transfer').text(res.data['转岗']||0);"),
    C(doc, "      $('#stat-train').text(res.data['培训']||0);"),
    C(doc, "      $('#stat-other').text(res.data['其他']||0);"),
    C(doc, '    }'),
    C(doc, '  });'),
    C(doc, '}'),
    C(doc, '// 查询/重置事件'),
    C(doc, "$('#btn-query').click(function(){"),
    C(doc, '  tableIns.reload({where:{'),
    C(doc, "    type:$('#filter-type').val(),"),
    C(doc, "    start_date:$('#filter-start').val(),"),
    C(doc, "    end_date:$('#filter-end').val()"),
    C(doc, '  }});'),
    C(doc, '});'),
    C(doc, "$('#btn-reset').click(function(){"),
    C(doc, "  $('#filter-type').val('');"),
    C(doc, "  $('#filter-start').val('');"),
    C(doc, "  $('#filter-end').val('');"),
    C(doc, "  tableIns.reload({where:{type:'',start_date:'',end_date:''}});"),
    C(doc, '});'),
    SP(doc),
    C(doc, '<!-- 类型标签模板（Jinja2 raw 包裹） -->'),
    C(doc, '{% raw %}'),
    C(doc, '<script type="text/html" id="typeTpl">'),
    C(doc, '  <span class="type-tag type-{{d.type}}">{{d.type}}</span>'),
    C(doc, '</script>'),
    C(doc, '{% endraw %}'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: blueprints/predict.py — GET 列表 + 统计 API'),
    C(doc, "@predict_bp.route('/api/interventions', methods=['GET'])"),
    C(doc, 'def api_interventions_list():'),
    C(doc, '    """干预记录分页列表，支持类型 + 日期筛选"""'),
    C(doc, '    try:'),
    C(doc, '        from db_model import Intervention'),
    C(doc, "        page = request.args.get('page', 1, type=int)"),
    C(doc, "        limit = request.args.get('limit', 15, type=int)"),
    C(doc, "        itype = request.args.get('type', '')"),
    C(doc, "        start_date = request.args.get('start_date', '')"),
    C(doc, "        end_date = request.args.get('end_date', '')"),
    C(doc, '        query = Intervention.query'),
    C(doc, '        if itype:'),
    C(doc, '            query = query.filter(Intervention.type == itype)'),
    C(doc, '        if start_date:'),
    C(doc, '            query = query.filter('),
    C(doc, '                Intervention.created_at >= datetime.strptime(...))'),
    C(doc, '        if end_date:'),
    C(doc, '            query = query.filter('),
    C(doc, '                Intervention.created_at <= datetime.strptime(...))'),
    C(doc, '        pagination = query.order_by(Intervention.created_at.desc())'),
    C(doc, '            .paginate(page=page, per_page=limit, error_out=False)'),
    C(doc, '        data = []'),
    C(doc, '        for inv in pagination.items:'),
    C(doc, '            emp = inv.employee  # SQLAlchemy relationship 自动联查'),
    C(doc, '            data.append({'),
    C(doc, "                'id': inv.id, 'employee_id': inv.employee_id,"),
    C(doc, "                'employee_number': emp.EmployeeNumber if emp else '',"),
    C(doc, "                'department': emp.Department if emp else '',"),
    C(doc, "                'job_role': emp.job_detail.JobRole if emp else '',"),
    C(doc, "                'type': inv.type,"),
    C(doc, "                'description_short': (inv.description or '')[:30],"),
    C(doc, "                'result': inv.result or '',"),
    C(doc, "                'operator': inv.operator,"),
    C(doc, "                'created_at': inv.created_at.strftime('%Y-%m-%d %H:%M')"),
    C(doc, '            })'),
    C(doc, "        return jsonify({'code':0, 'data':data, 'count':pagination.total})"),
    C(doc, '    except Exception as e:'),
    C(doc, "        return jsonify({'code':1,'msg':str(e)})"),
    SP(doc),
    C(doc, "@predict_bp.route('/api/interventions/stats', methods=['GET'])"),
    C(doc, 'def api_interventions_stats():'),
    C(doc, '    """按类型统计干预次数（供统计卡片使用）"""'),
    C(doc, "    from sqlalchemy import func"),
    C(doc, '    total = Intervention.query.count()'),
    C(doc, '    type_counts = db.session.query('),
    C(doc, '        Intervention.type, func.count(Intervention.id)'),
    C(doc, '    ).group_by(Intervention.type).all()'),
    C(doc, "    stats = {'total': total}"),
    C(doc, '    for t, cnt in type_counts:'),
    C(doc, '        stats[t] = cnt'),
    C(doc, "    for t in ['调薪','转岗','面谈','培训','其他']:  # 补全缺失类型"),
    C(doc, "        if t not in stats: stats[t] = 0"),
    C(doc, "    return jsonify({'code':0,'data':stats})"),
])

# ============================================================
# 2.3 员工干预时间线
# ============================================================
print('2.3 ...')
insert_section(doc, '2.4 干预效果统计 API', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码】'),
    LABEL(doc, '📄 位置: templates/interventions.html — 员工信息卡片 + CSS 时间线弹窗'),
    G(doc, '/* ===== CSS 时间线样式 ===== */'),
    C(doc, '.timeline {'),
    C(doc, '  position: relative; padding-left: 30px;'),
    C(doc, '}'),
    C(doc, '.timeline::before {  /* 左侧竖线 */'),
    C(doc, "  content: ''; position: absolute;"),
    C(doc, '  left: 10px; top: 0; bottom: 0;'),
    C(doc, '  width: 2px; background: #e4e7ed;'),
    C(doc, '}'),
    C(doc, '.timeline-item {'),
    C(doc, '  position: relative; margin-bottom: 20px;'),
    C(doc, '  padding: 12px 16px; background: #f9fafb;'),
    C(doc, '  border-radius: 8px; border-left: 3px solid #409eff;'),
    C(doc, '}'),
    C(doc, '.timeline-item::before {  /* 蓝色圆点 */'),
    C(doc, "  content: ''; position: absolute;"),
    C(doc, '  left: -28px; top: 12px;'),
    C(doc, '  width: 10px; height: 10px; border-radius: 50%;'),
    C(doc, '  background: #409eff; border: 2px solid #fff;'),
    C(doc, '  box-shadow: 0 0 0 2px #409eff;'),
    C(doc, '}'),
    C(doc, '.emp-card {  /* 深蓝渐变员工信息卡片 */'),
    C(doc, '  background: linear-gradient(135deg, #1B3A5C, #2a5180);'),
    C(doc, '  border-radius: 12px; padding: 20px; color: #fff;'),
    C(doc, '  margin-bottom: 18px; display: flex; gap: 16px;'),
    C(doc, '}'),
    SP(doc),
    G(doc, '/* ===== 点击查看详情 → AJAX 获取时间线 ===== */'),
    C(doc, 'function showEmployeeTimeline(empId) {'),
    C(doc, '  var loadIdx = layer.load(1);'),
    C(doc, "  $.get('/predict/api/interventions/employee/' + empId, function(r) {"),
    C(doc, '    layer.close(loadIdx);'),
    C(doc, '    if(r.code !== 0) { layer.msg("加载失败"); return; }'),
    C(doc, '    var emp = r.data.employee;'),
    C(doc, '    // 渲染员工信息卡片'),
    C(doc, "    var cardHtml = '<div style=\"display:flex;gap:20px;\">' +"),
    C(doc, "      '<div><h3 style=\"margin:0 0 8px;\">'+emp.dept+' - '+emp.role+'</h3>' +"),
    C(doc, "      '<p>司龄:'+emp.tenure+'年 | 月薪:¥'+emp.income+'</p>' +"),
    C(doc, "      '<p>年龄:'+emp.age+' | 加班:'+emp.overtime+'</p></div></div>';"),
    C(doc, "    $('#emp-card').html(cardHtml);"),
    C(doc, '    // 渲染干预历史时间线'),
    C(doc, '    var records = r.data.interventions;'),
    C(doc, "    $('#timeline-count').text('（共 '+records.length+' 条记录）');"),
    C(doc, '    if(records.length === 0) {'),
    C(doc, "      $('#timeline-body').html('<p style=\"color:#999;\">暂无干预记录</p>');"),
    C(doc, '    } else {'),
    C(doc, '      var html = "";'),
    C(doc, '      records.forEach(function(item) {'),
    C(doc, "        var icon = {'调薪':'💰','面谈':'💬','转岗':'🔄','培训':'📚','其他':'📋'};"),
    C(doc, '        html += "<div class=\'timeline-item\'>" +'),
    C(doc, '          "<strong>"+(icon[item.type]||"")+" "+item.type+"</strong>" +'),
    C(doc, '          "<small style=\'color:#8c939d\'> "+item.created_at+" | "+item.operator+"</small>" +'),
    C(doc, '          "<p style=\'margin-top:6px\'>"+(item.description||"")+"</p>" +'),
    C(doc, '          (item.result ? "<p style=\'color:#5FB878\'>✓ 处理结果: "+item.result+"</p>" : "") +'),
    C(doc, '          "</div>";'),
    C(doc, '      });'),
    C(doc, "      $('#timeline-body').html(html);"),
    C(doc, '    }'),
    C(doc, '  });'),
    C(doc, '}'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: blueprints/predict.py — GET /predict/api/interventions/employee/<id>'),
    C(doc, "@predict_bp.route('/api/interventions/employee/<int:emp_id>', methods=['GET'])"),
    C(doc, 'def api_interventions_employee(emp_id):'),
    C(doc, '    """获取某员工的完整信息 + 全部干预记录（时间线数据）"""'),
    C(doc, '    try:'),
    C(doc, '        # 联查 employee_base + job_detail + attrition_risk 三表'),
    C(doc, '        emp = db.session.query('),
    C(doc, '            EmployeeBase, JobDetail, AttritionRisk'),
    C(doc, '        ).outerjoin(JobDetail, EmployeeBase.EmployeeNumber =='),
    C(doc, '            JobDetail.EmployeeNumber).outerjoin('),
    C(doc, '            AttritionRisk, EmployeeBase.EmployeeNumber =='),
    C(doc, '            AttritionRisk.EmployeeNumber).filter('),
    C(doc, '            EmployeeBase.EmployeeNumber == emp_id).first()'),
    C(doc, "        if not emp: return jsonify({'code':404,'msg':'员工不存在'})"),
    C(doc, '        e, j, a = emp'),
    C(doc, "        employee_info = {  # 员工信息（供前端卡片渲染）"),
    C(doc, "            'id': e.EmployeeNumber, 'age': e.Age or 0,"),
    C(doc, "            'dept': (e.Department or '').strip(),"),
    C(doc, "            'role': j.JobRole if j else '',"),
    C(doc, "            'income': int(j.MonthlyIncome) if j and j.MonthlyIncome else 0,"),
    C(doc, "            'tenure': int(a.YearsAtCompany) if a and a.YearsAtCompany else 0,"),
    C(doc, "            'gender': e.Gender or '', 'overtime': a.OverTime if a else '',"),
    C(doc, "        }"),
    C(doc, '        # 干预记录（时间倒序）'),
    C(doc, '        records = Intervention.query.filter_by('),
    C(doc, '            employee_id=emp_id).order_by('),
    C(doc, '            Intervention.created_at.desc()).all()'),
    C(doc, '        timeline = [{'),
    C(doc, "            'id': r.id, 'type': r.type,"),
    C(doc, "            'description': r.description or '', 'result': r.result or '',"),
    C(doc, "            'operator': r.operator or '',"),
    C(doc, "            'created_at': r.created_at.strftime('%Y-%m-%d %H:%M:%S')"),
    C(doc, '        } for r in records]'),
    C(doc, "        return jsonify({'code':0,'data':{"),
    C(doc, "            'employee': employee_info, 'interventions': timeline}})"),
    C(doc, '    except Exception as e:'),
    C(doc, "        return jsonify({'code':1,'msg':str(e)})"),
])

# ============================================================
# 2.4 干预效果统计
# ============================================================
print('2.4 ...')
insert_section(doc, '任务三：操作日志系统', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码 — 可视化页面】'),
    LABEL(doc, '📄 位置: templates/effectiveness.html — 效果对比可视化页'),
    C(doc, '<!-- KPI 统计卡片：高风险总数 + 已干预 + 未干预 -->'),
    C(doc, '<div class="stat-grid">'),
    C(doc, '  <div class="stat-card card-risk">'),
    C(doc, '    <div class="num" id="risk-total">--</div>'),
    C(doc, '    <div class="label">高风险员工总数(≥70%)</div>'),
    C(doc, '  </div>'),
    C(doc, '  <div class="stat-card card-intervened">'),
    C(doc, '    <div class="num" id="iv-total">--</div>'),
    C(doc, '    <div class="label">已干预员工</div>'),
    C(doc, '    <div class="sub" id="iv-sub">离职人数 --</div>'),
    C(doc, '  </div>'),
    C(doc, '  <div class="stat-card card-not">'),
    C(doc, '    <div class="num" id="ni-total">--</div>'),
    C(doc, '    <div class="label">未干预员工</div>'),
    C(doc, '    <div class="sub" id="ni-sub">离职人数 --</div>'),
    C(doc, '  </div>'),
    C(doc, '</div>'),
    SP(doc),
    G(doc, '/* ECharts 双图表: 离职率柱状图对比 + 人数分布饼图 */'),
    C(doc, 'var bar = echarts.init(document.getElementById("bar-chart"));'),
    C(doc, 'bar.setOption({'),
    C(doc, "  tooltip: {trigger:'axis'},"),
    C(doc, "  xAxis: {type:'category', data:['已干预','未干预']},"),
    C(doc, "  yAxis: {type:'value', name:'离职率 (%)', max:100},"),
    C(doc, '  series: [{type:"bar", data: [iv.rate, ni.rate],'),
    C(doc, '    itemStyle: {color: function(p){'),
    C(doc, "      return p.dataIndex === 0 ? '#409EFF' : '#FF9800';"),
    C(doc, '    }}, barWidth: "50%",'),
    C(doc, '    label: {show:true, formatter:"{c}%", fontSize:16, fontWeight:"bold"}'),
    C(doc, '  }]'),
    C(doc, '});'),
    SP(doc),
    C(doc, '// 详细数据对比表'),
    C(doc, 'var iv_stay = iv.total - iv.attrition;  // 已干预-未离职'),
    C(doc, 'var ni_stay = ni.total - ni.attrition;  // 未干预-未离职'),
    C(doc, "$('#detail-body').html("),
    C(doc, "  '<tr><td>已干预</td><td>'+iv.total+'</td>"),
    C(doc, "  <td>'+iv.attrition+'</td><td>'+iv_stay+'</td>"),
    C(doc, "  <td style=\"color:#5FB878;font-weight:600\">'+iv.rate+'%</td></tr>' +"),
    C(doc, "  '<tr><td>未干预</td><td>'+ni.total+'</td>"),
    C(doc, "  <td>'+ni.attrition+'</td><td>'+ni_stay+'</td>"),
    C(doc, "  <td style=\"color:#FF5722;font-weight:600\">'+ni.rate+'%</td></tr>');"),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: blueprints/predict.py — 效果统计核心算法'),
    C(doc, "def api_interventions_effectiveness():"),
    C(doc, '    """统计逻辑：'),
    C(doc, '    1. 批量预测所有员工, 筛选 probability >= 0.7 的高风险'),
    C(doc, '    2. 查询已有干预的员工 ID 集合'),
    C(doc, '    3. 分已干预/未干预两组, 对比 Attrition=Yes 的离职率'),
    C(doc, '    """'),
    C(doc, '    # ① 联查三表 + ML 批量预测'),
    C(doc, '    results = db.session.query('),
    C(doc, '        EmployeeBase, JobDetail, AttritionRisk'),
    C(doc, '    ).join(JobDetail).join(AttritionRisk).all()'),
    C(doc, '    df = pd.DataFrame([{...} for r in results])'),
    C(doc, '    # 补充缺失特征列'),
    C(doc, "    for col, val in default_fill.items():"),
    C(doc, "        if col not in df.columns: df[col] = val"),
    C(doc, '    probs = batch_predict(df)         # ML 模型预测'),
    C(doc, "    df['probability'] = probs"),
    C(doc, "    high_risk = df[df['probability'] >= 0.7].copy()  # 筛选高风险"),
    C(doc, ''),
    C(doc, '    # ② 获取已有干预的员工 ID 集合'),
    C(doc, '    intervened_ids = set(r[0] for r in'),
    C(doc, '        db.session.query(Intervention.employee_id).distinct().all())'),
    C(doc, ''),
    C(doc, '    # ③ 分组统计'),
    C(doc, "    intervened = high_risk[high_risk['EmployeeNumber'].astype(int)"),
    C(doc, '        .isin(intervened_ids)]'),
    C(doc, "    not_intervened = high_risk[~high_risk['EmployeeNumber'].astype(int)"),
    C(doc, '        .isin(intervened_ids)]'),
    C(doc, ''),
    C(doc, '    def calc(df_group):  # 计算: 总数 / 离职数 / 离职率'),
    C(doc, '        t = len(df_group)'),
    C(doc, "        a = int((df_group['Attrition'].str.strip()"),
    C(doc, "            .str.lower().isin(['yes','1'])).sum()) if t else 0"),
    C(doc, '        r = round(a/t*100,1) if t else 0'),
    C(doc, "        return {'total':t, 'attrition':a, 'rate':r}"),
    C(doc, ''),
    C(doc, "    return jsonify({'code':0,'data':{"),
    C(doc, "        'high_risk_total': len(high_risk),"),
    C(doc, "        'intervened': calc(intervened),"),
    C(doc, "        'not_intervened': calc(not_intervened)"),
    C(doc, '    }})'),
    SP(doc),
    G(doc, '// 返回示例：已干预员工离职率 0%，未干预 80.8%'),
])

# ============================================================
# 3.1 日志工具函数
# ============================================================
print('3.1 ...')
insert_section(doc, '3.2 关键操作埋点', [
    S(doc), TITLE(doc, '【核心代码】'),
    LABEL(doc, '📄 位置: db_model.py — OperationLog 数据模型'),
    C(doc, 'class OperationLog(db.Model):'),
    C(doc, '    """系统操作日志 —— 所有关键操作可追溯"""'),
    C(doc, "    __tablename__ = 'operation_logs'"),
    C(doc, '    id = db.Column(db.Integer, primary_key=True, autoincrement=True)'),
    C(doc, "    user_id = db.Column(db.Integer, db.ForeignKey('users.id'),"),
    C(doc, '        nullable=True, comment="操作人用户ID")'),
    C(doc, "    username = db.Column(db.String(50), default='',"),
    C(doc, '        comment="操作人姓名（冗余存储，便于查询）")'),
    C(doc, "    action = db.Column(db.String(50), nullable=False,"),
    C(doc, '        comment="操作类型: 登录成功/删除员工/批量预测/...")'),
    C(doc, "    target = db.Column(db.String(200), default='',"),
    C(doc, '        comment="操作对象: 员工编号/用户名/文件名")'),
    C(doc, "    detail = db.Column(db.Text, default='', comment='补充描述')"),
    C(doc, "    ip = db.Column(db.String(50), default='', comment='客户端IP')"),
    C(doc, '    created_at = db.Column(db.DateTime, default=datetime.now)'),
    C(doc, "    user = db.relationship('User', backref='operation_logs')"),
    SP(doc),
    LABEL(doc, '📄 位置: utils/logger.py — log_action() 完整实现'),
    C(doc, '"""'),
    C(doc, '操作日志工具函数 —— 一行代码记录日志'),
    C(doc, '用法: from utils.logger import log_action'),
    C(doc, "      log_action('删除员工', '员工编号1001', '姓名：张三，部门：研发部')"),
    C(doc, '"""'),
    C(doc, 'from flask import session, request, has_request_context'),
    C(doc, 'from db_model import db, OperationLog'),
    C(doc, ''),
    C(doc, "def log_action(action, target='', detail=''):"),
    C(doc, '    """'),
    C(doc, '    记录操作日志。一行调用即可。'),
    C(doc, '    自动从 session 获取 user_id / username，'),
    C(doc, '    从 request.remote_addr 获取 IP 地址。'),
    C(doc, '    若不在 Flask 请求上下文中（命令行/定时任务）则静默跳过。'),
    C(doc, '    日志写入失败不会抛出异常，不影响主业务流程。'),
    C(doc, '    """'),
    C(doc, '    if not has_request_context():'),
    C(doc, '        return  # 非请求环境静默跳过'),
    C(doc, '    try:'),
    C(doc, "        user_id = session.get('user_id')"),
    C(doc, "        username = session.get('username', '')"),
    C(doc, "        ip = request.remote_addr or ''"),
    C(doc, '        log_entry = OperationLog('),
    C(doc, '            user_id=user_id, username=username,'),
    C(doc, '            action=action, target=str(target),'),
    C(doc, '            detail=str(detail), ip=ip)'),
    C(doc, '        db.session.add(log_entry)'),
    C(doc, '        db.session.commit()'),
    C(doc, '    except Exception:'),
    C(doc, '        pass  # 日志记录失败不应影响主业务'),
    SP(doc),
    G(doc, '# ======== 使用示例 —— 任何视图函数中只需一行 ========'),
    C(doc, "log_action('登录成功', username, f'角色: {user.role}')"),
    C(doc, "log_action('删除员工', f'员工#{emp_id}', '')"),
    C(doc, "log_action('批量预测', '', f'共 {len(results)} 名员工')"),
    C(doc, "log_action('发送报告邮件', email, f'附件: {filename}')"),
    C(doc, "log_action('创建用户', username, f'姓名：{real_name}')"),
    SP(doc),
    LABEL(doc, '📄 位置: utils/__init__.py — 包初始化文件（使 utils 成为 Python 包）'),
    C(doc, '# 空文件，仅标记 utils 为 Python 包，'),
    C(doc, '# 使得 from utils.logger import log_action 可以正常导入'),
])

# ============================================================
# 3.2 关键操作埋点
# ============================================================
print('3.2 ...')
insert_section(doc, '3.3 日志查看页', [
    S(doc), TITLE(doc, '【核心代码】'),
    LABEL(doc, '📄 位置: app.py — 登录认证相关埋点 (3处)'),
    C(doc, '# ===== login 视图: 验证通过后 ====='),
    C(doc, "session['user_id'] = user.id"),
    C(doc, "session['username'] = user.username"),
    C(doc, "session['role'] = user.role"),
    C(doc, 'from utils.logger import log_action'),
    C(doc, "log_action('登录成功', username, f'角色: {user.role}')"),
    C(doc, ''),
    C(doc, '# ===== login 视图: 验证失败后 ====='),
    C(doc, 'if not user or not check_password_hash(user.password, password):'),
    C(doc, '    from utils.logger import log_action'),
    C(doc, "    log_action('登录失败', username or '', '密码错误或用户不存在')"),
    C(doc, "    return jsonify({'code': 401, 'msg': '用户名或密码错误'})"),
    C(doc, ''),
    C(doc, '# ===== logout 视图 ====='),
    C(doc, 'def logout():'),
    C(doc, '    from utils.logger import log_action'),
    C(doc, "    log_action('退出登录', '', '')"),
    C(doc, '    session.clear()'),
    C(doc, "    return render_template('login.html')"),
    SP(doc),
    LABEL(doc, '📄 位置: blueprints/employee.py — 员工管理埋点 (3处)'),
    C(doc, '# ===== add_employee: commit 成功后 ====='),
    C(doc, 'db.session.add(emp)'),
    C(doc, 'db.session.commit()'),
    C(doc, 'from utils.logger import log_action'),
    C(doc, "log_action('新增员工', f'员工编号{emp_id}', f'姓名：{name}，部门：{dept}')"),
    C(doc, ''),
    C(doc, '# ===== edit_employee: commit 成功后 ====='),
    C(doc, 'db.session.commit()'),
    C(doc, "log_action('编辑员工', f'员工编号{emp_id}',"),
    C(doc, "    f'更新字段：{changed_fields}')"),
    C(doc, ''),
    C(doc, '# ===== delete_employee: commit 成功后 ====='),
    C(doc, 'db.session.delete(emp)'),
    C(doc, 'db.session.commit()'),
    C(doc, "log_action('删除员工', f'员工编号{emp_id}', '')"),
    SP(doc),
    LABEL(doc, '📄 位置: blueprints/predict.py — 预测+报告+干预埋点 (6处)'),
    C(doc, "# 单次预测完成: log_action('单次预测', f'员工#{eid}', f'风险:{level}')"),
    C(doc, "# 批量预测完成: log_action('批量预测', '', f'共{len(res)}名员工')"),
    C(doc, "# PNG报告生成: log_action('生成报告', filename, f'类型:PNG')"),
    C(doc, "# 报告下载: log_action('下载报告', filename, '')"),
    C(doc, "# SMTP邮件发送: log_action('发送报告邮件', email, f'附件:{basename}')"),
    C(doc, "# 干预记录添加: log_action('添加干预记录', f'员工#{emp_id}', desc[:60])"),
    SP(doc),
    LABEL(doc, '📄 位置: blueprints/user.py — 用户管理埋点 (2处)'),
    C(doc, '# ===== 创建用户成功后 ====='),
    C(doc, 'from utils.logger import log_action'),
    C(doc, "log_action('创建用户', username, f'姓名：{real_name}，角色：user')"),
    C(doc, ''),
    C(doc, '# ===== 修改密码成功后 ====='),
    C(doc, 'user.password = generate_password_hash(new_pwd)'),
    C(doc, 'db.session.commit()'),
    C(doc, "log_action('修改密码', user.username, '密码已更新，需重新登录')"),
])

# ============================================================
# 3.3 日志查看页
# ============================================================
print('3.3 ...')
insert_section(doc, '3.4 我的操作记录', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码】'),
    LABEL(doc, '📄 位置: templates/log_list.html — 筛选栏 + Layui 表格 + 颜色标签'),
    C(doc, '<!-- 筛选栏：操作人 + 类型 + 时间范围 -->'),
    C(doc, '<div class="filter-bar">'),
    C(doc, '  <input id="filter-username" placeholder="输入用户名">'),
    C(doc, '  <select id="filter-action"><option value="">全部类型</option></select>'),
    C(doc, '  <input type="text" id="filter-start" placeholder="开始日期" readonly>'),
    C(doc, '  <span>—</span>'),
    C(doc, '  <input type="text" id="filter-end" placeholder="结束日期" readonly>'),
    C(doc, '  <button id="btn-query">查询</button>'),
    C(doc, '  <button id="btn-reset">重置</button>'),
    C(doc, '  <span id="total-info">共 0 条</span>'),
    C(doc, '</div>'),
    SP(doc),
    C(doc, '// Layui 表格渲染'),
    C(doc, 'var tableIns = table.render({'),
    C(doc, "  elem: '#log-table', url: '/predict/api/logs',"),
    C(doc, '  page: true, limit: 15,'),
    C(doc, "  where: {username:'', action:'', start_date:'', end_date:''},"),
    C(doc, '  cols: [[ '),
    C(doc, "    {field:'created_at', title:'操作时间', width:170},"),
    C(doc, "    {field:'username', title:'操作人', width:100},"),
    C(doc, "    {field:'action', title:'操作类型', width:120, templet:'#actionTpl'},"),
    C(doc, "    {field:'target', title:'操作对象', width:160},"),
    C(doc, "    {field:'detail_short', title:'描述', minWidth:180},"),
    C(doc, "    {field:'ip', title:'IP地址', width:130},"),
    C(doc, '  ]],'),
    C(doc, "  done: function(res){ $('#total-info').text('共 '+res.count+' 条'); }"),
    C(doc, '});'),
    SP(doc),
    C(doc, '// 加载操作类型下拉（带统计数）'),
    C(doc, 'function loadActionTypes() {'),
    C(doc, "  $.get('/predict/api/logs/actions', function(res) {"),
    C(doc, '    if(res.code===0) {'),
    C(doc, "      var html = '<option value=\"\">全部类型</option>';"),
    C(doc, '      res.data.forEach(function(item) {'),
    C(doc, "        html += '<option value=\"'+item.name+'\">'"),
    C(doc, "          + item.name + ' ('+item.count+')</option>';"),
    C(doc, '      });'),
    C(doc, "      $('#filter-action').html(html);"),
    C(doc, '    }'),
    C(doc, '  });'),
    C(doc, '}'),
    C(doc, '// 查询/重置'),
    C(doc, "$('#btn-query').click(function(){ tableIns.reload({where:{"),
    C(doc, "  username:$('#filter-username').val().trim(),"),
    C(doc, "  action:$('#filter-action').val(),"),
    C(doc, "  start_date:$('#filter-start').val(),"),
    C(doc, "  end_date:$('#filter-end').val()"),
    C(doc, '}}); });'),
    SP(doc),
    G(doc, '<!-- 操作类型颜色标签（14种） -->'),
    C(doc, '.action-tag { display:inline-block; padding:2px 10px; border-radius:12px;'),
    C(doc, '  font-size:12px; font-weight:600; color:#fff; }'),
    C(doc, '.action-登录成功{background:#5FB878;} .action-登录失败{background:#FF5722;}'),
    C(doc, '.action-新增员工{background:#409EFF;} .action-编辑员工{background:#FF9800;}'),
    C(doc, '.action-删除员工{background:#FF5722;} .action-批量预测{background:#6366f1;}'),
    C(doc, '.action-生成报告{background:#14B8A6;} .action-发送报告邮件{background:#F59E0B;}'),
    SP(doc),
    G(doc, '<!-- Jinja2 + Layui 冲突解决: {% raw %} 包裹 -->'),
    C(doc, '{% raw %}'),
    C(doc, '<script type="text/html" id="actionTpl">'),
    C(doc, '  <span class="action-tag action-{{d.action}}">{{d.action}}</span>'),
    C(doc, '</script>'),
    C(doc, '{% endraw %}'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: blueprints/predict.py — 日志查询 API'),
    C(doc, "@predict_bp.route('/api/logs', methods=['GET'])"),
    C(doc, 'def api_logs_list():'),
    C(doc, '    """分页查询 + 操作人/类型/时间三维筛选"""'),
    C(doc, "    username = request.args.get('username', '')"),
    C(doc, "    action = request.args.get('action', '')"),
    C(doc, "    start_date = request.args.get('start_date', '')"),
    C(doc, "    end_date = request.args.get('end_date', '')"),
    C(doc, "    page = int(request.args.get('page', 1))"),
    C(doc, "    limit = int(request.args.get('limit', 15))"),
    C(doc, '    query = OperationLog.query'),
    C(doc, '    if username:  # 操作人模糊匹配'),
    C(doc, "        query = query.filter(OperationLog.username.like(f'%{username}%'))"),
    C(doc, '    if action:    # 操作类型精确匹配'),
    C(doc, '        query = query.filter(OperationLog.action == action)'),
    C(doc, '    if start_date:  # 时间范围筛选'),
    C(doc, '        query = query.filter(OperationLog.created_at >= '),
    C(doc, "            dt.strptime(start_date, '%Y-%m-%d'))"),
    C(doc, '    if end_date:'),
    C(doc, '        query = query.filter(OperationLog.created_at <= '),
    C(doc, "            dt.strptime(end_date + ' 23:59:59', '%Y-%m-%d %H:%M:%S'))"),
    C(doc, '    total = query.count()'),
    C(doc, '    logs = query.order_by(OperationLog.created_at.desc())'),
    C(doc, '        .offset((page-1)*limit).limit(limit).all()'),
    C(doc, '    data = [{'),
    C(doc, "        'id': log.id, 'username': log.username or '',"),
    C(doc, "        'action': log.action, 'target': log.target or '',"),
    C(doc, "        'detail': log.detail or '',"),
    C(doc, "        'detail_short': (log.detail or '')[:50],"),
    C(doc, "        'ip': log.ip or '',"),
    C(doc, "        'created_at': log.created_at.strftime('%Y-%m-%d %H:%M:%S')"),
    C(doc, '    } for log in logs]'),
    C(doc, "    return jsonify({'code':0, 'data':data, 'count':total})"),
    SP(doc),
    C(doc, "@predict_bp.route('/api/logs/actions', methods=['GET'])"),
    C(doc, 'def api_logs_actions():'),
    C(doc, '    """返回所有操作类型及出现次数（供筛选下拉）"""'),
    C(doc, '    actions = db.session.query('),
    C(doc, '        OperationLog.action, func.count(OperationLog.id)'),
    C(doc, '    ).group_by(OperationLog.action).order_by(func.count(...).desc()).all()'),
    C(doc, "    return jsonify({'code':0,'data':["),
    C(doc, "        {'name':a,'count':c} for a,c in actions])}"),
    SP(doc),
    LABEL(doc, '📄 位置: app.py — 页面路由'),
    C(doc, "@app.route('/log/list')"),
    C(doc, 'def log_list():'),
    C(doc, "    if 'user_id' not in session: return redirect(url_for('index'))"),
    C(doc, "    return render_template('log_list.html')"),
])

# ============================================================
# 3.4 我的操作记录
# ============================================================
print('3.4 ...')
insert_section(doc, '3.5 日志统计 API', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码】'),
    LABEL(doc, '📄 位置: templates/user/my_logs.html — 个人操作日志页'),
    G(doc, '<!-- 与 log_list.html 几乎一致, 3 点区别: -->'),
    G(doc, '<!-- ① 数据源: url → /log/api/my -->'),
    G(doc, '<!-- ② 表格去掉 username 列（都是自己） -->'),
    G(doc, '<!-- ③ 筛选栏去掉操作人输入框 -->'),
    C(doc, 'var tableIns = table.render({'),
    C(doc, "  elem:'#log-table', url:'/log/api/my', page:true, limit:15,"),
    C(doc, '  cols:[[ '),
    C(doc, "    {field:'created_at', title:'操作时间', width:170},"),
    C(doc, "    {field:'action', title:'操作类型', width:120, templet:'#actionTpl'},"),
    C(doc, "    {field:'target', title:'操作对象', width:160},"),
    C(doc, "    {field:'detail_short', title:'描述', minWidth:200},"),
    C(doc, "    {field:'ip', title:'IP地址', width:130}"),
    C(doc, '    // ↑ 仅5列，无操作人列'),
    C(doc, '  ]]'),
    C(doc, '});'),
    SP(doc),
    LABEL(doc, '📄 位置: templates/user/profile.html — 个人中心入口链接'),
    C(doc, '<!-- 在"修改密码"卡片前插入，仅当前用户可见 -->'),
    C(doc, '<div class="card" style="text-align:center;padding:18px 32px;">'),
    C(doc, '  <a href="/log/my" target="mainFrame"'),
    C(doc, '     style="color:#409eff;font-size:15px;text-decoration:none;">'),
    C(doc, '    <i class="layui-icon layui-icon-log"></i> 我的操作记录'),
    C(doc, '  </a>'),
    C(doc, '</div>'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: app.py — 我的日志 API（按 user_id 过滤）'),
    C(doc, "@app.route('/log/api/my')"),
    C(doc, 'def api_my_logs():'),
    C(doc, '    """仅返回当前登录用户的操作日志"""'),
    C(doc, "    if 'user_id' not in session:"),
    C(doc, "        return jsonify({'code':401,'msg':'请先登录'})"),
    C(doc, '    # 核心：按 user_id 过滤，与管理员版 API 的唯一区别'),
    C(doc, '    query = OperationLog.query.filter('),
    C(doc, "        OperationLog.user_id == session['user_id']"),
    C(doc, '    )'),
    C(doc, "    if request.args.get('action'):"),
    C(doc, '        query = query.filter(OperationLog.action == ...)'),
    C(doc, '    if start_date:'),
    C(doc, '        query = query.filter(OperationLog.created_at >= ...)'),
    C(doc, '    # ... 分页、排序、返回逻辑与 api_logs_list 相同 ...'),
    C(doc, '    total = query.count()'),
    C(doc, '    logs = query.order_by(OperationLog.created_at.desc())'),
    C(doc, '        .offset((page-1)*limit).limit(limit).all()'),
    C(doc, "    return jsonify({'code':0,'data':data,'count':total})"),
    SP(doc),
    LABEL(doc, '📄 位置: app.py — 我的日志页面路由'),
    C(doc, "@app.route('/log/my')"),
    C(doc, 'def my_logs_page():'),
    C(doc, "    if 'user_id' not in session: return redirect(url_for('index'))"),
    C(doc, "    return render_template('user/my_logs.html')"),
])

# ============================================================
# 3.5 日志统计
# ============================================================
print('3.5 ...')
insert_section(doc, '3.6（选做）旧日志清理', [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码 — 可视化页面】'),
    LABEL(doc, '📄 位置: templates/log_stats.html — 今日日志统计页'),
    C(doc, '<!-- 渐变大 KPI 卡片：今日操作总次数 -->'),
    C(doc, '<div class="kpi-card" style="background:linear-gradient(135deg,#667eea,#764ba2);">'),
    C(doc, '  <div class="kpi-num" id="total-num">0</div>'),
    C(doc, '  <div class="kpi-label">今日操作总次数</div>'),
    C(doc, '</div>'),
    SP(doc),
    G(doc, '/* ECharts 南丁格尔玫瑰饼图 —— 操作类型分布 */'),
    C(doc, 'var pie = echarts.init(document.getElementById("pie-chart"));'),
    C(doc, 'pie.setOption({'),
    C(doc, "  tooltip: {trigger:'item', formatter:'{b}: {c} 次 ({d}%)'},"),
    C(doc, '  legend: {type:"scroll", bottom:0, textStyle:{fontSize:11}},'),
    C(doc, '  series: [{type:"pie", radius:["40%","68%"], center:["50%","43%"],'),
    C(doc, '    roseType:"area",  // 南丁格尔玫瑰图'),
    C(doc, '    itemStyle: {borderRadius:6, borderColor:"#fff", borderWidth:2},'),
    C(doc, '    label: {formatter:"{b}\\n{d}%", fontSize:11},'),
    C(doc, '    data: types.map(function(t,i){'),
    C(doc, '      return {value:t.count, name:t.action,'),
    C(doc, '        itemStyle:{color:colors[i%colors.length]}};'),
    C(doc, '    })'),
    C(doc, '  }]'),
    C(doc, '});'),
    SP(doc),
    G(doc, '/* 右侧排行：进度条 + 颜色标签 */'),
    C(doc, 'types.forEach(function(t,i){'),
    C(doc, '  var pct = Math.round(t.count / maxCount * 100);'),
    C(doc, '  var barColor = colors[i % colors.length];'),
    C(doc, '  html += "<div>" +'),
    C(doc, '    "<div style=\"display:flex;justify-content:space-between;\">" +'),
    C(doc, '    "<span class=\"action-tag action-"+t.action+"\">"+t.action+"</span>" +'),
    C(doc, '    "<span>"+t.count+" 次</span></div>" +'),
    C(doc, '    "<div style=\"background:#ebeef5;height:6px;border-radius:3px;\">" +'),
    C(doc, '    "<div style=\"background:"+barColor+";height:6px;border-radius:3px;'),
    C(doc, '      width:"+pct+"%;\"></div></div></div>";'),
    C(doc, '});'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: app.py — GET /log/api/stats/today'),
    C(doc, "@app.route('/log/api/stats/today')"),
    C(doc, 'def api_log_stats_today():'),
    C(doc, '    """返回今日操作总数 + 各类型分布（供可视化调用）"""'),
    C(doc, '    from datetime import datetime as dt'),
    C(doc, '    from sqlalchemy import func'),
    C(doc, '    today_start = dt.now().replace('),
    C(doc, '        hour=0, minute=0, second=0, microsecond=0)'),
    C(doc, '    query = OperationLog.query.filter('),
    C(doc, '        OperationLog.created_at >= today_start)'),
    C(doc, '    total = query.count()  # 今日操作总次数'),
    C(doc, '    type_counts = db.session.query('),
    C(doc, '        OperationLog.action, func.count(OperationLog.id)'),
    C(doc, '    ).filter(OperationLog.created_at >= today_start)'),
    C(doc, '     .group_by(OperationLog.action)'),
    C(doc, '     .order_by(func.count(OperationLog.id).desc()).all()'),
    C(doc, "    return jsonify({'code':0,'data':{"),
    C(doc, "        'today_total': total,"),
    C(doc, "        'type_distribution': ["),
    C(doc, "            {'action':a, 'count':c} for a,c in type_counts]}})"),
    SP(doc),
    G(doc, '# 返回示例: {"today_total": 218, "type_distribution": ['),
    G(doc, '#   {"action": "批量预测", "count": 41},'),
    G(doc, '#   {"action": "登录成功", "count": 7}, ...]}'),
])

# ============================================================
# 3.6 旧日志清理
# ============================================================
print('3.6 ...')
# 3.6 是文档最后一个任务，代码插在末尾
last_p = doc.paragraphs[-1]
paras_36 = [
    S(doc), TITLE(doc, '【核心代码】'), FE(doc, '【前端代码】'),
    LABEL(doc, '📄 位置: templates/log_list.html — 红色清理按钮 + 确认弹窗'),
    C(doc, '<!-- 筛选栏新增红色"清理旧日志"按钮 -->'),
    C(doc, '<button class="layui-btn layui-btn-sm layui-btn-danger" id="btn-clean"'),
    C(doc, '        style="height:36px;line-height:36px;border-radius:6px;margin-left:auto;">'),
    C(doc, '  <i class="layui-icon layui-icon-delete"></i> 清理旧日志'),
    C(doc, '</button>'),
    SP(doc),
    G(doc, '/* JS: 二次确认 → AJAX POST */'),
    C(doc, "$('#btn-clean').click(function(){"),
    C(doc, '  layer.confirm('),
    C(doc, "    '确认删除 <strong style=\"color:#FF5722;\">90 天前</strong> 的日志记录吗？',"),
    C(doc, "    {title:'清理旧日志', icon:3, btn:['确认清理','取消'], btnAlign:'c'},"),
    C(doc, '    function(idx){'),
    C(doc, '      layer.close(idx);'),
    C(doc, '      var loadIdx = layer.load(1);'),
    C(doc, "      $.post('/log/api/clean', function(res){"),
    C(doc, '        layer.close(loadIdx);'),
    C(doc, '        if(res.code === 0){'),
    C(doc, "          layer.msg('成功清理 ' + res.deleted + ' 条旧日志', {icon:1});"),
    C(doc, '          tableIns.reload();  // 刷新表格'),
    C(doc, '        } else { layer.msg(res.msg, {icon:2}); }'),
    C(doc, "      }).fail(function(){ layer.close(loadIdx); layer.msg('请求失败',{icon:2}); });"),
    C(doc, '    }'),
    C(doc, '  );'),
    C(doc, '});'),
    SP(doc),
    BE(doc, '【后端代码】'),
    LABEL(doc, '📄 位置: app.py — POST /log/api/clean（仅管理员可调用）'),
    C(doc, "@app.route('/log/api/clean', methods=['POST'])"),
    C(doc, 'def api_log_clean():'),
    C(doc, '    """清理 90 天前的日志记录，返回删除条数"""'),
    C(doc, "    if 'user_id' not in session:"),
    C(doc, "        return jsonify({'code':401,'msg':'请先登录'})"),
    C(doc, "    if session.get('role') != 'admin':"),
    C(doc, "        return jsonify({'code':403,'msg':'仅管理员可操作'})"),
    C(doc, '    try:'),
    C(doc, '        from db_model import OperationLog'),
    C(doc, '        from datetime import datetime as dt, timedelta'),
    C(doc, '        cutoff = dt.now() - timedelta(days=90)  # 90天前的时间点'),
    C(doc, '        count = OperationLog.query.filter('),
    C(doc, '            OperationLog.created_at < cutoff  # 早于90天前'),
    C(doc, '        ).delete()  # SQLAlchemy 批量删除'),
    C(doc, '        db.session.commit()'),
    C(doc, "        return jsonify({'code':0,"),
    C(doc, "            'msg':f'成功清理 {count} 条旧日志',"),
    C(doc, "            'deleted': count})"),
    C(doc, '    except Exception as e:'),
    C(doc, '        db.session.rollback()'),
    C(doc, "        return jsonify({'code':1,'msg':str(e)})"),
]
for p in reversed(paras_36):
    last_p._element.addnext(p._element)

# ===== 保存 =====
print(f'\nSaving to: {DOC}')
doc.save(DOC)
print('Done!')
